#!/bin/bash
### 
### 

for file in [AS]*_muc1;
do perl -e '
($id,$fasta)=@ARGV;
open(ID,$id);
while (<ID>) {
    s/\r?\n//;
    /^>?(\S+)/;
    $ids{$1}++;
}
$num_ids = keys %ids;
open(F, $fasta);
$s_read = $s_wrote = $print_it = 0;
while (<F>) {
    if (/^>(\S+)/) {
        $s_read++;
        if ($ids{$1}) {
            $s_wrote++;
            $print_it = 1;
            delete $ids{$1}
        }
        else {
            $print_it = 0
        }

    };
    if ($print_it) {
        print $_
    }
};
END {
    warn "Searched $s_read FASTA records.\nFound $s_wrote IDs out of $num_ids in the ID list.\n"
}
' $file new_evolution_of_muc1.fasta > $file.fasta;
done

for file in [AS]*_muc5;
do perl -e '
($id,$fasta)=@ARGV;
open(ID,$id);
while (<ID>) {
    s/\r?\n//;
    /^>?(\S+)/;
    $ids{$1}++;
}
$num_ids = keys %ids;
open(F, $fasta);
$s_read = $s_wrote = $print_it = 0;
while (<F>) {
    if (/^>(\S+)/) {
        $s_read++;
        if ($ids{$1}) {
            $s_wrote++;
            $print_it = 1;
            delete $ids{$1}
        }
        else {
            $print_it = 0
        }

    };
    if ($print_it) {
        print $_
    }
};
END {
    warn "Searched $s_read FASTA records.\nFound $s_wrote IDs out of $num_ids in the ID list.\n"
}
' $file new_evolution_of_muc5.fasta > $file.fasta;
done

for file in [AS]*_sftpa;
do perl -e '
($id,$fasta)=@ARGV;
open(ID,$id);
while (<ID>) {
    s/\r?\n//;
    /^>?(\S+)/;
    $ids{$1}++;
}
$num_ids = keys %ids;
open(F, $fasta);
$s_read = $s_wrote = $print_it = 0;
while (<F>) {
    if (/^>(\S+)/) {
        $s_read++;
        if ($ids{$1}) {
            $s_wrote++;
            $print_it = 1;
            delete $ids{$1}
        }
        else {
            $print_it = 0
        }

    };
    if ($print_it) {
        print $_
    }
};
END {
    warn "Searched $s_read FASTA records.\nFound $s_wrote IDs out of $num_ids in the ID list.\n"
}
' $file new_evolution_of_sftpa.fasta > $file.fasta;
done

for file in [AS]*_sftpd;
do perl -e '
($id,$fasta)=@ARGV;
open(ID,$id);
while (<ID>) {
    s/\r?\n//;
    /^>?(\S+)/;
    $ids{$1}++;
}
$num_ids = keys %ids;
open(F, $fasta);
$s_read = $s_wrote = $print_it = 0;
while (<F>) {
    if (/^>(\S+)/) {
        $s_read++;
        if ($ids{$1}) {
            $s_wrote++;
            $print_it = 1;
            delete $ids{$1}
        }
        else {
            $print_it = 0
        }

    };
    if ($print_it) {
        print $_
    }
};
END {
    warn "Searched $s_read FASTA records.\nFound $s_wrote IDs out of $num_ids in the ID list.\n"
}
' $file new_evolution_of_sftpd.fasta > $file.fasta;
done
