#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=100:00:00
#SBATCH --mem=80gb
#SBATCH --job-name=phyluce_probeset
#SBATCH --error=phyluceprobeset2.err
#SBATCH --output=phyluceprobeset2.out
#SBATCH --partition=long

#export MAMBA_ROOT_PREFIX=/opt/Micromamba/
#eval "$(/opt/bin/Micromamba/1.5.8-0/bin/micromamba shell hook -s posix)"
#micromamba activate phyluce

cd ~/UCE/
phyluce_probe_run_multiple_lastzs_sqlite --db 2genome-actino-lastz/2genome-actino-fasta/2general_alignment-all.sqlite
	--output actino/2genomes-of-all-species/
	--scaffoldlist Actino_Acipen_A_oxyrinchus Actino_Acipen_A_ruthenus Actino_Acipen_H_huso Actino_Acipen_P_spathula Actino_Elopo_A_affinis Actino_Elopo_A_anguilla Actino_Elopo_A_glossodonta Actino_Elopo_A_goreensis Actino_Elopo_G_javanicus Actino_Elopo_M_atlanticus Actino_Elopo_M_cyprinoides Actino_Eupercaria_A_latus Actino_Eupercaria_C_aceratus Actino_Eupercaria_C_gunnari Actino_Eupercaria_C_striata Actino_Eupercaria_C_undulatus Actino_Eupercaria_D_eleginoides Actino_Eupercaria_E_fuscoguttatus Actino_Eupercaria_E_lanceolatus Actino_Eupercaria_E_spectabile Actino_Eupercaria_G_aculeatus Actino_Eupercaria_L_mixtus Actino_Eupercaria_M_dolomieu Actino_Eupercaria_N_celidotus Actino_Eupercaria_P_flavesces Actino_Eupercaria_P_georgianus Actino_Eupercaria_P_pungitius Actino_Eupercaria_S_aurata Actino_Eupercaria_S_chuatsi Actino_Eupercaria_S_umbrosus Actino_Eupercaria_T_bernacchii Actino_Eupercaria_X_novacula Actino_Holostei_A_calva Actino_Holostei_A_spatula Actino_Holostei_L_oculatus Actino_Neotele_G_chalcogrammus Actino_Neotele_G_macrocephalus Actino_Neotele_G_morhua Actino_Neotele_L_incognitus Actino_Neotele_Perco_A_calliptera Actino_Neotele_Perco_A_centrarchus Actino_Neotele_Perco_A_ocellaris Actino_Neotele_Perco_A_polyacanthus Actino_Neotele_Perco_A_testudineus Actino_Neotele_Perco_F_heteroclitus Actino_Neotele_Perco_G_acuticeps Actino_Neotele_Perco_G_affinis Actino_Neotele_Perco_H_zosterae Actino_Neotele_Perco_K_caucasica Actino_Neotele_Perco_M_zebra Actino_Neotele_Perco_N_furzeri Actino_Neotele_Perco_O_aureus Actino_Neotele_Perco_O_latipes Actino_Neotele_Perco_O_melastigma Actino_Neotele_Perco_O_niloticus Actino_Neotele_Perco_P_eques Actino_Neotele_Perco_P_magnuspinnatus Actino_Neotele_Perco_P_prolifica Actino_Neotele_Perco_P_reticulata Actino_Neotele_Perco_P_taeniolatus Actino_Neotele_Perco_S_aureovittata Actino_Neotele_Perco_S_scombrus Actino_Neotele_Perco_S_scovelli Actino_Neotele_Perco_T_albacares Actino_Neotele_Perco_T_maccoyii Actino_Neotele_Perco_X_maculatus Actino_Poly_E_calabarius Actino_Poly_P_bichir Actino_Poly_P_senegalus Actino_Tele_Osteoglo_B_brachyistius Actino_Tele_Osteoglo_P_kingsleyae Actino_Tele_Osteoglo_S_formosus Actino_Tele_Oto_A_alosa Actino_Tele_Oto_A_mexicanus Actino_Tele_Oto_A_sapidissima Actino_Tele_Oto_C_auratus Actino_Tele_Oto_C_carassius Actino_Tele_Oto_C_carpio Actino_Tele_Oto_C_gibelio Actino_Tele_Oto_C_harengus Actino_Tele_Oto_C_macropomum Actino_Tele_Oto_C_molitorella Actino_Tele_Oto_D_aesculapii Actino_Tele_Oto_D_rerio Actino_Tele_Oto_E_electricus Actino_Tele_Oto_L_rohita Actino_Tele_Oto_M_anguillicaudatus Actino_Tele_Oto_M_asiaticus Actino_Tele_Oto_N_graeffei Actino_Tele_Oto_O_macrolepis Actino_Tele_Oto_P_nattereri Actino_Tele_Oto_P_tetrazona Actino_Tele_Oto_S_meridionalis Actino_Tele_Oto_S_pichardus Actino_Tele_Oto_T_dalaica Actino_Tele_Oto_T_rosa Actino_Tele_Oto_X_texanus Actino_Tele_Prota_C_clupeaformis Actino_Tele_Prota_D_pectoralis Actino_Tele_Prota_E_lucius Actino_Tele_Prota_O_gorbucha Actino_Tele_Prota_O_keta Actino_Tele_Prota_O_kisutch Actino_Tele_Prota_O_mykiss Actino_Tele_Prota_S_namaycush Actino_Tele_Prota_S_salar Actino_Tele_Prota_S_trutta Actino_Tele_Sto_H_transpacificus Actino_Tele_Sto_O_eperlanus
	--genome-base-path actino/
	--probefile 2genome-actino-lastz/2genome-actino-fasta/2actinopterygii-v1-master-probe-list-DUPE-SCREENED.fasta --cores 24

cd ~/UCE/
phyluce_probe_run_multiple_lastzs_lastzs_sqlite --db 2genome-sarco-lastz/2genome-sarco-fasta/2general_alignment-all.sqlite
	--output sarco/2genomes-of-all-species/
	--scaffoldlist Sarco_Amphi_B_gargarizans Sarco_Amphi_G_seraphini Sarco_Amphi_M_unicolor Sarco_Amphi_R_temporaria Sarco_Amphi_X_laevis Sarco_Amphi_X_tropicalis Sarco_Mammals_A_flavipes Sarco_Mammals_C_canadensis Sarco_Mammals_D_dama Sarco_Mammals_E_fuscus Sarco_Mammals_E_quagga Sarco_Mammals_F_cattus Sarco_Mammals_H_amphibius Sarco_Mammals_H_sapiens Sarco_Mammals_L_catta Sarco_Mammals_L_europeaus Sarco_Mammals_L_lutra Sarco_Mammals_M_domestica Sarco_Mammals_M_musculus Sarco_Mammals_N_vison Sarco_Mammals_O_aires Sarco_Mammals_O_orca Sarco_Mammals_P_abelii Sarco_Mammals_P_tigris Sarco_Mammals_P_tryglodytes Sarco_Mammals_R_norvegicus Sarco_Mammals_S_araneus Sarco_Mammals_S_harrisii Sarco_Mammals_S_scrofa Sarco_Mammals_T_aculeatus Sarco_Mammals_T_truncatus Sarco_Mammals_T_vulpecula Sarco_Mammals_V_lagopus Sarco_Reptilia_Archo_A_chrysaetos Sarco_Reptilia_Archo_A_cygnoides Sarco_Reptilia_Archo_C_anna Sarco_Reptilia_Archo_C_japonica Sarco_Reptilia_Archo_C_livia Sarco_Reptilia_Archo_D_pubescens Sarco_Reptilia_Archo_F_cherrug Sarco_Reptilia_Archo_F_peregrinus Sarco_Reptilia_Archo_G_gallus Sarco_Reptilia_Archo_M_gallopavo Sarco_Reptilia_Archo_R_tridactyla Sarco_Reptilia_C_mydas Sarco_Reptilia_C_picta Sarco_Reptilia_G_evgoodei Sarco_Reptilia_Lepdo_A_carolinensis Sarco_Reptilia_Lepdo_A_parsina Sarco_Reptilia_Lepdo_H_binoei Sarco_Reptilia_Lepdo_H_capensis Sarco_Reptilia_Lepdo_P_muralis Sarco_Reptilia_Lepdo_Z_vivipara Sarco_Reptilia_M_terrapin Sarco_Reptilia_Passeri_C_hawaiiensis Sarco_Reptilia_Passeri_C_moneduloides Sarco_Reptilia_Passeri_H_mexicanus Sarco_Reptilia_Passeri_O_melanoleuca Sarco_Reptilia_Passeri_P_domesticus Sarco_Reptilia_Passeri_S_canaria Sarco_Reptilia_Passeri_S_habroptila Sarco_Reptilia_Archo_C_nicobarica Sarco_Reptilia_P_sinensis Sarco_Reptilia_Archo_P_fasciata Sarco_Amphi_B_bufo Sarco_Amphi_H_boettgeri Sarco_Amphi_R_bivittatum Sarco_Mammals_B_taurus Sarco_Mammals_C_lupus Sarco_Mammals_E_caballus Sarco_Mammals_G_gorilla Sarco_Mammals_L_africana  Sarco_Mammals_O_anatinus Sarco_Reptilia_Archo_A_platyrhynchos Sarco_Reptilia_Archo_H_harpyja Sarco_Reptilia_C_caretta Sarco_Reptilia_Croco_A_mississipiensis Sarco_Reptilia_Lepdo_N_naja Sarco_Reptilia_Lepdo_T_elegans Sarco_Reptilia_Passeri_L_discolor
	--genome-base-path sarco/
	--probefile 2genome-sarco-lastz/2genome-sarco-fasta/2sarcopterygii-v1-master-probe-list-DUPE-SCREENED.fasta --cores 24

phyluce_probe_run_multiple_lastzs_sqlite --db 2genome-sarco-lastz/2genome-sarco-fasta/2general_alignment-all.sqlite
	--output sarco/2genomes-of-all-species/
	--scaffoldlist 1_Sarco_Amphi_P_waltl 2_Sarco_Amphi_P_waltl Sarco_Coelacanth_L_chalumnae 1_Sarco_Dipnoi_N_forsteri 2_Sarco_Dipnoi_N_forsteri 3_Sarco_Dipnoi_N_forsteri 1_Sarco_Dipnoi_P_annectens 2_Sarco_Dipnoi_P_annectens
	--genome-base-path sarco/
	--probefile 2genome-sarco-lastz/2genome-sarco-fasta/2sarcopterygii-v1-master-probe-list-DUPE-SCREENED.fasta --cores 24

phyluce_probe_run_multiple_lastzs_sqlite --db 2genome-sarco-lastz/2genome-sarco-fasta/3general_alignment-all.sqlite 
	--output sarco/2genomes-of-all-species/ 
	--scaffoldlist Sarco_Dipnoi_P_annectens_1_1  --genome-base-path sarco/ 
	--probefile 2genome-sarco-lastz/2genome-sarco-fasta/2sarcopterygii-v1-master-probe-list-DUPE-SCREENED.fasta --cores 24
